apiVersion: v1
kind: Service
metadata:
  name: addressbook-service
spec:
  # Use LoadBalancer for cloud environments or NodePort for local clusters like Minikube
  type: LoadBalancer 
  selector:
    app: addressbook
  ports:
    - protocol: TCP
      port: 80          # External port to access the app
      targetPort: 8080  # Port where Tomcat is listening inside the pod
